# Autogenerated wrapper script for POMDPSolve_jll for aarch64-apple-darwin
export pomdpfg, pomdpsolve, pomdptest, pomdptools

JLLWrappers.@generate_wrapper_header("POMDPSolve")
JLLWrappers.@declare_executable_product(pomdpfg)
JLLWrappers.@declare_executable_product(pomdpsolve)
JLLWrappers.@declare_executable_product(pomdptest)
JLLWrappers.@declare_executable_product(pomdptools)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        pomdpfg,
        "bin/pomdp-fg",
    )

    JLLWrappers.@init_executable_product(
        pomdpsolve,
        "bin/pomdp-solve",
    )

    JLLWrappers.@init_executable_product(
        pomdptest,
        "bin/pomdp-test",
    )

    JLLWrappers.@init_executable_product(
        pomdptools,
        "bin/pomdp-tools",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
